/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    fn extract_bit(byte: u8, index: usize) -> bool {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        Self::extract_bit(byte, index)
    }
    #[inline]
    pub unsafe fn raw_get_bit(this: *const Self, index: usize) -> bool {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            *(core::ptr::addr_of!((*this).storage) as *const u8).offset(byte_index as isize)
        };
        Self::extract_bit(byte, index)
    }
    #[inline]
    fn change_bit(byte: u8, index: usize, val: bool) -> u8 {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        if val {
            byte | mask
        } else {
            byte & !mask
        }
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        *byte = Self::change_bit(*byte, index, val);
    }
    #[inline]
    pub unsafe fn raw_set_bit(this: *mut Self, index: usize, val: bool) {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            (core::ptr::addr_of_mut!((*this).storage) as *mut u8).offset(byte_index as isize)
        };
        unsafe { *byte = Self::change_bit(*byte, index, val) };
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if self.get_bit(i + bit_offset) {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub unsafe fn raw_get(this: *const Self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if unsafe { Self::raw_get_bit(this, i + bit_offset) } {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            self.set_bit(index + bit_offset, val_bit_is_set);
        }
    }
    #[inline]
    pub unsafe fn raw_set(this: *mut Self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            unsafe { Self::raw_set_bit(this, index + bit_offset, val_bit_is_set) };
        }
    }
}
pub const UCP_ENTITY_NAME_MAX: u32 = 32;
pub const UCP_VERSION_MAJOR_SHIFT: u32 = 24;
pub const UCP_VERSION_MINOR_SHIFT: u32 = 16;
pub const UCP_API_MAJOR: u32 = 1;
pub const UCP_API_MINOR: u32 = 18;
impl ucs_memory_type {
    pub const UCS_MEMORY_TYPE_UNKNOWN: ucs_memory_type = ucs_memory_type::UCS_MEMORY_TYPE_LAST;
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucs_memory_type {
    UCS_MEMORY_TYPE_HOST = 0,
    UCS_MEMORY_TYPE_CUDA = 1,
    UCS_MEMORY_TYPE_CUDA_MANAGED = 2,
    UCS_MEMORY_TYPE_ROCM = 3,
    UCS_MEMORY_TYPE_ROCM_MANAGED = 4,
    UCS_MEMORY_TYPE_RDMA = 5,
    UCS_MEMORY_TYPE_ZE_HOST = 6,
    UCS_MEMORY_TYPE_ZE_DEVICE = 7,
    UCS_MEMORY_TYPE_ZE_MANAGED = 8,
    UCS_MEMORY_TYPE_LAST = 9,
}
pub use self::ucs_memory_type as ucs_memory_type_t;
unsafe extern "C" {
    pub static mut ucs_memory_type_names: [*const ::std::os::raw::c_char; 0usize];
}
unsafe extern "C" {
    pub static mut ucs_memory_type_descs: [*const ::std::os::raw::c_char; 0usize];
}
#[repr(i8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucs_status_t {
    UCS_OK = 0,
    UCS_INPROGRESS = 1,
    UCS_ERR_NO_MESSAGE = -1,
    UCS_ERR_NO_RESOURCE = -2,
    UCS_ERR_IO_ERROR = -3,
    UCS_ERR_NO_MEMORY = -4,
    UCS_ERR_INVALID_PARAM = -5,
    UCS_ERR_UNREACHABLE = -6,
    UCS_ERR_INVALID_ADDR = -7,
    UCS_ERR_NOT_IMPLEMENTED = -8,
    UCS_ERR_MESSAGE_TRUNCATED = -9,
    UCS_ERR_NO_PROGRESS = -10,
    UCS_ERR_BUFFER_TOO_SMALL = -11,
    UCS_ERR_NO_ELEM = -12,
    UCS_ERR_SOME_CONNECTS_FAILED = -13,
    UCS_ERR_NO_DEVICE = -14,
    UCS_ERR_BUSY = -15,
    UCS_ERR_CANCELED = -16,
    UCS_ERR_SHMEM_SEGMENT = -17,
    UCS_ERR_ALREADY_EXISTS = -18,
    UCS_ERR_OUT_OF_RANGE = -19,
    UCS_ERR_TIMED_OUT = -20,
    UCS_ERR_EXCEEDS_LIMIT = -21,
    UCS_ERR_UNSUPPORTED = -22,
    UCS_ERR_REJECTED = -23,
    UCS_ERR_NOT_CONNECTED = -24,
    UCS_ERR_CONNECTION_RESET = -25,
    UCS_ERR_FIRST_LINK_FAILURE = -40,
    UCS_ERR_LAST_LINK_FAILURE = -59,
    UCS_ERR_FIRST_ENDPOINT_FAILURE = -60,
    UCS_ERR_ENDPOINT_TIMEOUT = -80,
    UCS_ERR_LAST_ENDPOINT_FAILURE = -89,
    UCS_ERR_LAST = -100,
}
pub type ucs_status_ptr_t = *mut ::std::os::raw::c_void;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type socklen_t = __socklen_t;
pub type sa_family_t = ::std::os::raw::c_ushort;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sockaddr {
    pub sa_family: sa_family_t,
    pub sa_data: [::std::os::raw::c_char; 14usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sockaddr_storage {
    pub ss_family: sa_family_t,
    pub __ss_padding: [::std::os::raw::c_char; 118usize],
    pub __ss_align: ::std::os::raw::c_ulong,
}
unsafe extern "C" {
    pub static mut ucs_async_mode_names: [*const ::std::os::raw::c_char; 0usize];
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucs_config_print_flags_t {
    UCS_CONFIG_PRINT_CONFIG = 1,
    UCS_CONFIG_PRINT_HEADER = 2,
    UCS_CONFIG_PRINT_DOC = 4,
    UCS_CONFIG_PRINT_HIDDEN = 8,
    UCS_CONFIG_PRINT_COMMENT_DEFAULT = 16,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucs_sock_addr {
    pub addr: *const sockaddr,
    pub addrlen: socklen_t,
}
pub type ucs_sock_addr_t = ucs_sock_addr;
pub type ucp_tag_recv_info_t = ucp_tag_recv_info;
pub type ucp_am_recv_param_t = ucp_am_recv_param;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_context {
    _unused: [u8; 0],
}
pub type ucp_context_h = *mut ucp_context;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_config {
    _unused: [u8; 0],
}
pub type ucp_config_t = ucp_config;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_ep {
    _unused: [u8; 0],
}
pub type ucp_ep_h = *mut ucp_ep;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_conn_request {
    _unused: [u8; 0],
}
pub type ucp_conn_request_h = *mut ucp_conn_request;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_address {
    _unused: [u8; 0],
}
pub type ucp_address_t = ucp_address;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_err_handling_mode_t {
    UCP_ERR_HANDLING_MODE_NONE = 0,
    UCP_ERR_HANDLING_MODE_PEER = 1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_rkey {
    _unused: [u8; 0],
}
pub type ucp_rkey_h = *mut ucp_rkey;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_mem {
    _unused: [u8; 0],
}
pub type ucp_mem_h = *mut ucp_mem;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_listener {
    _unused: [u8; 0],
}
pub type ucp_listener_h = *mut ucp_listener;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_mem_attr {
    pub field_mask: u64,
    pub address: *mut ::std::os::raw::c_void,
    pub length: usize,
    pub mem_type: ucs_memory_type_t,
}
pub type ucp_mem_attr_t = ucp_mem_attr;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_mem_attr_field {
    UCP_MEM_ATTR_FIELD_ADDRESS = 1,
    UCP_MEM_ATTR_FIELD_LENGTH = 2,
    UCP_MEM_ATTR_FIELD_MEM_TYPE = 4,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_worker {
    _unused: [u8; 0],
}
pub type ucp_worker_h = *mut ucp_worker;
pub type ucp_tag_t = u64;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_recv_desc {
    _unused: [u8; 0],
}
pub type ucp_tag_message_h = *mut ucp_recv_desc;
pub type ucp_datatype_t = u64;
pub type ucp_request_init_callback_t =
    ::std::option::Option<unsafe extern "C" fn(request: *mut ::std::os::raw::c_void)>;
pub type ucp_request_cleanup_callback_t =
    ::std::option::Option<unsafe extern "C" fn(request: *mut ::std::os::raw::c_void)>;
pub type ucp_send_callback_t = ::std::option::Option<
    unsafe extern "C" fn(request: *mut ::std::os::raw::c_void, status: ucs_status_t),
>;
pub type ucp_send_nbx_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        request: *mut ::std::os::raw::c_void,
        status: ucs_status_t,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
pub type ucp_err_handler_cb_t = ::std::option::Option<
    unsafe extern "C" fn(arg: *mut ::std::os::raw::c_void, ep: ucp_ep_h, status: ucs_status_t),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_err_handler {
    pub cb: ucp_err_handler_cb_t,
    pub arg: *mut ::std::os::raw::c_void,
}
pub type ucp_err_handler_t = ucp_err_handler;
pub type ucp_listener_accept_callback_t =
    ::std::option::Option<unsafe extern "C" fn(ep: ucp_ep_h, arg: *mut ::std::os::raw::c_void)>;
pub type ucp_listener_conn_callback_t = ::std::option::Option<
    unsafe extern "C" fn(conn_request: ucp_conn_request_h, arg: *mut ::std::os::raw::c_void),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_listener_conn_handler {
    pub cb: ucp_listener_conn_callback_t,
    pub arg: *mut ::std::os::raw::c_void,
}
pub type ucp_listener_conn_handler_t = ucp_listener_conn_handler;
pub type ucp_stream_recv_callback_t = ::std::option::Option<
    unsafe extern "C" fn(request: *mut ::std::os::raw::c_void, status: ucs_status_t, length: usize),
>;
pub type ucp_stream_recv_nbx_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        request: *mut ::std::os::raw::c_void,
        status: ucs_status_t,
        length: usize,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
pub type ucp_tag_recv_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        request: *mut ::std::os::raw::c_void,
        status: ucs_status_t,
        info: *mut ucp_tag_recv_info_t,
    ),
>;
pub type ucp_tag_recv_nbx_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        request: *mut ::std::os::raw::c_void,
        status: ucs_status_t,
        tag_info: *const ucp_tag_recv_info_t,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
pub type ucp_am_recv_data_nbx_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        request: *mut ::std::os::raw::c_void,
        status: ucs_status_t,
        length: usize,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_wakeup_event_types {
    UCP_WAKEUP_RMA = 1,
    UCP_WAKEUP_AMO = 2,
    UCP_WAKEUP_TAG_SEND = 4,
    UCP_WAKEUP_TAG_RECV = 8,
    UCP_WAKEUP_TX = 1024,
    UCP_WAKEUP_RX = 2048,
    UCP_WAKEUP_EDGE = 65536,
}
pub use self::ucp_wakeup_event_types as ucp_wakeup_event_t;
pub type ucp_am_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg: *mut ::std::os::raw::c_void,
        data: *mut ::std::os::raw::c_void,
        length: usize,
        reply_ep: ucp_ep_h,
        flags: ::std::os::raw::c_uint,
    ) -> ucs_status_t,
>;
pub type ucp_am_recv_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg: *mut ::std::os::raw::c_void,
        header: *const ::std::os::raw::c_void,
        header_length: usize,
        data: *mut ::std::os::raw::c_void,
        length: usize,
        param: *const ucp_am_recv_param_t,
    ) -> ucs_status_t,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_ep_params {
    pub field_mask: u64,
    pub address: *const ucp_address_t,
    pub err_mode: ucp_err_handling_mode_t,
    pub err_handler: ucp_err_handler_t,
    pub user_data: *mut ::std::os::raw::c_void,
    pub flags: ::std::os::raw::c_uint,
    pub sockaddr: ucs_sock_addr_t,
    pub conn_request: ucp_conn_request_h,
    pub name: *const ::std::os::raw::c_char,
    pub local_sockaddr: ucs_sock_addr_t,
}
pub type ucp_ep_params_t = ucp_ep_params;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_transport_entry_t {
    pub transport_name: *const ::std::os::raw::c_char,
    pub device_name: *const ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_transports_t {
    pub entries: *mut ucp_transport_entry_t,
    pub num_entries: ::std::os::raw::c_uint,
    pub entry_size: usize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_listener_accept_handler {
    pub cb: ucp_listener_accept_callback_t,
    pub arg: *mut ::std::os::raw::c_void,
}
pub type ucp_listener_accept_handler_t = ucp_listener_accept_handler;
unsafe extern "C" {
    pub fn ucp_request_is_completed(request: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn ucp_request_release(request: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn ucp_ep_destroy(ep: ucp_ep_h);
}
unsafe extern "C" {
    pub fn ucp_disconnect_nb(ep: ucp_ep_h) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_request_test(
        request: *mut ::std::os::raw::c_void,
        info: *mut ucp_tag_recv_info_t,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_rkey_pack(
        context: ucp_context_h,
        memh: ucp_mem_h,
        rkey_buffer_p: *mut *mut ::std::os::raw::c_void,
        size_p: *mut usize,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_rkey_buffer_release(rkey_buffer: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn ucp_ep_flush(ep: ucp_ep_h) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_worker_flush(worker: ucp_worker_h) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_put(
        ep: ucp_ep_h,
        buffer: *const ::std::os::raw::c_void,
        length: usize,
        remote_addr: u64,
        rkey: ucp_rkey_h,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_get(
        ep: ucp_ep_h,
        buffer: *mut ::std::os::raw::c_void,
        length: usize,
        remote_addr: u64,
        rkey: ucp_rkey_h,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_atomic_add32(
        ep: ucp_ep_h,
        add: u32,
        remote_addr: u64,
        rkey: ucp_rkey_h,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_atomic_add64(
        ep: ucp_ep_h,
        add: u64,
        remote_addr: u64,
        rkey: ucp_rkey_h,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_atomic_fadd32(
        ep: ucp_ep_h,
        add: u32,
        remote_addr: u64,
        rkey: ucp_rkey_h,
        result: *mut u32,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_atomic_fadd64(
        ep: ucp_ep_h,
        add: u64,
        remote_addr: u64,
        rkey: ucp_rkey_h,
        result: *mut u64,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_atomic_swap32(
        ep: ucp_ep_h,
        swap: u32,
        remote_addr: u64,
        rkey: ucp_rkey_h,
        result: *mut u32,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_atomic_swap64(
        ep: ucp_ep_h,
        swap: u64,
        remote_addr: u64,
        rkey: ucp_rkey_h,
        result: *mut u64,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_atomic_cswap32(
        ep: ucp_ep_h,
        compare: u32,
        swap: u32,
        remote_addr: u64,
        rkey: ucp_rkey_h,
        result: *mut u32,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_atomic_cswap64(
        ep: ucp_ep_h,
        compare: u64,
        swap: u64,
        remote_addr: u64,
        rkey: ucp_rkey_h,
        result: *mut u64,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_ep_modify_nb(ep: ucp_ep_h, params: *const ucp_ep_params_t) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_worker_get_address(
        worker: ucp_worker_h,
        address_p: *mut *mut ucp_address_t,
        address_length_p: *mut usize,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_ep_close_nb(ep: ucp_ep_h, mode: ::std::os::raw::c_uint) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_ep_flush_nb(
        ep: ucp_ep_h,
        flags: ::std::os::raw::c_uint,
        cb: ucp_send_callback_t,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_worker_set_am_handler(
        worker: ucp_worker_h,
        id: u16,
        cb: ucp_am_callback_t,
        arg: *mut ::std::os::raw::c_void,
        flags: u32,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_am_send_nb(
        ep: ucp_ep_h,
        id: u16,
        buffer: *const ::std::os::raw::c_void,
        count: usize,
        datatype: ucp_datatype_t,
        cb: ucp_send_callback_t,
        flags: ::std::os::raw::c_uint,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_stream_send_nb(
        ep: ucp_ep_h,
        buffer: *const ::std::os::raw::c_void,
        count: usize,
        datatype: ucp_datatype_t,
        cb: ucp_send_callback_t,
        flags: ::std::os::raw::c_uint,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_stream_recv_nb(
        ep: ucp_ep_h,
        buffer: *mut ::std::os::raw::c_void,
        count: usize,
        datatype: ucp_datatype_t,
        cb: ucp_stream_recv_callback_t,
        length: *mut usize,
        flags: ::std::os::raw::c_uint,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_tag_send_nb(
        ep: ucp_ep_h,
        buffer: *const ::std::os::raw::c_void,
        count: usize,
        datatype: ucp_datatype_t,
        tag: ucp_tag_t,
        cb: ucp_send_callback_t,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_tag_send_nbr(
        ep: ucp_ep_h,
        buffer: *const ::std::os::raw::c_void,
        count: usize,
        datatype: ucp_datatype_t,
        tag: ucp_tag_t,
        req: *mut ::std::os::raw::c_void,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_tag_send_sync_nb(
        ep: ucp_ep_h,
        buffer: *const ::std::os::raw::c_void,
        count: usize,
        datatype: ucp_datatype_t,
        tag: ucp_tag_t,
        cb: ucp_send_callback_t,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_tag_recv_nb(
        worker: ucp_worker_h,
        buffer: *mut ::std::os::raw::c_void,
        count: usize,
        datatype: ucp_datatype_t,
        tag: ucp_tag_t,
        tag_mask: ucp_tag_t,
        cb: ucp_tag_recv_callback_t,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_tag_recv_nbr(
        worker: ucp_worker_h,
        buffer: *mut ::std::os::raw::c_void,
        count: usize,
        datatype: ucp_datatype_t,
        tag: ucp_tag_t,
        tag_mask: ucp_tag_t,
        req: *mut ::std::os::raw::c_void,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_tag_msg_recv_nb(
        worker: ucp_worker_h,
        buffer: *mut ::std::os::raw::c_void,
        count: usize,
        datatype: ucp_datatype_t,
        message: ucp_tag_message_h,
        cb: ucp_tag_recv_callback_t,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_put_nbi(
        ep: ucp_ep_h,
        buffer: *const ::std::os::raw::c_void,
        length: usize,
        remote_addr: u64,
        rkey: ucp_rkey_h,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_put_nb(
        ep: ucp_ep_h,
        buffer: *const ::std::os::raw::c_void,
        length: usize,
        remote_addr: u64,
        rkey: ucp_rkey_h,
        cb: ucp_send_callback_t,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_get_nbi(
        ep: ucp_ep_h,
        buffer: *mut ::std::os::raw::c_void,
        length: usize,
        remote_addr: u64,
        rkey: ucp_rkey_h,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_get_nb(
        ep: ucp_ep_h,
        buffer: *mut ::std::os::raw::c_void,
        length: usize,
        remote_addr: u64,
        rkey: ucp_rkey_h,
        cb: ucp_send_callback_t,
    ) -> ucs_status_ptr_t;
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_atomic_post_op_t {
    UCP_ATOMIC_POST_OP_ADD = 0,
    UCP_ATOMIC_POST_OP_AND = 1,
    UCP_ATOMIC_POST_OP_OR = 2,
    UCP_ATOMIC_POST_OP_XOR = 3,
    UCP_ATOMIC_POST_OP_LAST = 4,
}
unsafe extern "C" {
    pub fn ucp_atomic_post(
        ep: ucp_ep_h,
        opcode: ucp_atomic_post_op_t,
        value: u64,
        op_size: usize,
        remote_addr: u64,
        rkey: ucp_rkey_h,
    ) -> ucs_status_t;
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_atomic_fetch_op_t {
    UCP_ATOMIC_FETCH_OP_FADD = 0,
    UCP_ATOMIC_FETCH_OP_SWAP = 1,
    UCP_ATOMIC_FETCH_OP_CSWAP = 2,
    UCP_ATOMIC_FETCH_OP_FAND = 3,
    UCP_ATOMIC_FETCH_OP_FOR = 4,
    UCP_ATOMIC_FETCH_OP_FXOR = 5,
    UCP_ATOMIC_FETCH_OP_LAST = 6,
}
unsafe extern "C" {
    pub fn ucp_atomic_fetch_nb(
        ep: ucp_ep_h,
        opcode: ucp_atomic_fetch_op_t,
        value: u64,
        result: *mut ::std::os::raw::c_void,
        op_size: usize,
        remote_addr: u64,
        rkey: ucp_rkey_h,
        cb: ucp_send_callback_t,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_worker_flush_nb(
        worker: ucp_worker_h,
        flags: ::std::os::raw::c_uint,
        cb: ucp_send_callback_t,
    ) -> ucs_status_ptr_t;
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_ep_close_mode {
    UCP_EP_CLOSE_MODE_FORCE = 0,
    UCP_EP_CLOSE_MODE_FLUSH = 1,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucs_thread_mode_t {
    UCS_THREAD_MODE_SINGLE = 0,
    UCS_THREAD_MODE_SERIALIZED = 1,
    UCS_THREAD_MODE_MULTI = 2,
    UCS_THREAD_MODE_LAST = 3,
}
unsafe extern "C" {
    pub static mut ucs_thread_mode_names: [*const ::std::os::raw::c_char; 0usize];
}
pub type ucs_cpu_mask_t = ::std::os::raw::c_ulong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucs_cpu_set_t {
    pub ucs_bits: [ucs_cpu_mask_t; 16usize],
}
pub type FILE = _IO_FILE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_marker {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_codecvt {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_wide_data {
    _unused: [u8; 0],
}
pub type _IO_lock_t = ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_FILE {
    pub _flags: ::std::os::raw::c_int,
    pub _IO_read_ptr: *mut ::std::os::raw::c_char,
    pub _IO_read_end: *mut ::std::os::raw::c_char,
    pub _IO_read_base: *mut ::std::os::raw::c_char,
    pub _IO_write_base: *mut ::std::os::raw::c_char,
    pub _IO_write_ptr: *mut ::std::os::raw::c_char,
    pub _IO_write_end: *mut ::std::os::raw::c_char,
    pub _IO_buf_base: *mut ::std::os::raw::c_char,
    pub _IO_buf_end: *mut ::std::os::raw::c_char,
    pub _IO_save_base: *mut ::std::os::raw::c_char,
    pub _IO_backup_base: *mut ::std::os::raw::c_char,
    pub _IO_save_end: *mut ::std::os::raw::c_char,
    pub _markers: *mut _IO_marker,
    pub _chain: *mut _IO_FILE,
    pub _fileno: ::std::os::raw::c_int,
    pub _bitfield_align_1: [u32; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 3usize]>,
    pub _short_backupbuf: [::std::os::raw::c_char; 1usize],
    pub _old_offset: __off_t,
    pub _cur_column: ::std::os::raw::c_ushort,
    pub _vtable_offset: ::std::os::raw::c_schar,
    pub _shortbuf: [::std::os::raw::c_char; 1usize],
    pub _lock: *mut _IO_lock_t,
    pub _offset: __off64_t,
    pub _codecvt: *mut _IO_codecvt,
    pub _wide_data: *mut _IO_wide_data,
    pub _freeres_list: *mut _IO_FILE,
    pub _freeres_buf: *mut ::std::os::raw::c_void,
    pub _prevchain: *mut *mut _IO_FILE,
    pub _mode: ::std::os::raw::c_int,
    pub _unused2: [::std::os::raw::c_char; 20usize],
}
impl _IO_FILE {
    #[inline]
    pub fn _flags2(&self) -> ::std::os::raw::c_int {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 24u8) as u32) }
    }
    #[inline]
    pub fn set__flags2(&mut self, val: ::std::os::raw::c_int) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 24u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn _flags2_raw(this: *const Self) -> ::std::os::raw::c_int {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 3usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                0usize,
                24u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set__flags2_raw(this: *mut Self, val: ::std::os::raw::c_int) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 3usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                0usize,
                24u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn new_bitfield_1(_flags2: ::std::os::raw::c_int) -> __BindgenBitfieldUnit<[u8; 3usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 3usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 24u8, {
            let _flags2: u32 = unsafe { ::std::mem::transmute(_flags2) };
            _flags2 as u64
        });
        __bindgen_bitfield_unit
    }
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_params_field {
    UCP_PARAM_FIELD_FEATURES = 1,
    UCP_PARAM_FIELD_REQUEST_SIZE = 2,
    UCP_PARAM_FIELD_REQUEST_INIT = 4,
    UCP_PARAM_FIELD_REQUEST_CLEANUP = 8,
    UCP_PARAM_FIELD_TAG_SENDER_MASK = 16,
    UCP_PARAM_FIELD_MT_WORKERS_SHARED = 32,
    UCP_PARAM_FIELD_ESTIMATED_NUM_EPS = 64,
    UCP_PARAM_FIELD_ESTIMATED_NUM_PPN = 128,
    UCP_PARAM_FIELD_NAME = 256,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_feature {
    UCP_FEATURE_TAG = 1,
    UCP_FEATURE_RMA = 2,
    UCP_FEATURE_AMO32 = 4,
    UCP_FEATURE_AMO64 = 8,
    UCP_FEATURE_WAKEUP = 16,
    UCP_FEATURE_STREAM = 32,
    UCP_FEATURE_AM = 64,
    UCP_FEATURE_EXPORTED_MEMH = 128,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_worker_params_field {
    UCP_WORKER_PARAM_FIELD_THREAD_MODE = 1,
    UCP_WORKER_PARAM_FIELD_CPU_MASK = 2,
    UCP_WORKER_PARAM_FIELD_EVENTS = 4,
    UCP_WORKER_PARAM_FIELD_USER_DATA = 8,
    UCP_WORKER_PARAM_FIELD_EVENT_FD = 16,
    UCP_WORKER_PARAM_FIELD_FLAGS = 32,
    UCP_WORKER_PARAM_FIELD_NAME = 64,
    UCP_WORKER_PARAM_FIELD_AM_ALIGNMENT = 128,
    UCP_WORKER_PARAM_FIELD_CLIENT_ID = 256,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_worker_flags_t {
    UCP_WORKER_FLAG_IGNORE_REQUEST_LEAK = 1,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_listener_params_field {
    UCP_LISTENER_PARAM_FIELD_SOCK_ADDR = 1,
    UCP_LISTENER_PARAM_FIELD_ACCEPT_HANDLER = 2,
    UCP_LISTENER_PARAM_FIELD_CONN_HANDLER = 4,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_worker_address_flags_t {
    UCP_WORKER_ADDRESS_FLAG_NET_ONLY = 1,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_ep_params_field {
    UCP_EP_PARAM_FIELD_REMOTE_ADDRESS = 1,
    UCP_EP_PARAM_FIELD_ERR_HANDLING_MODE = 2,
    UCP_EP_PARAM_FIELD_ERR_HANDLER = 4,
    UCP_EP_PARAM_FIELD_USER_DATA = 8,
    UCP_EP_PARAM_FIELD_SOCK_ADDR = 16,
    UCP_EP_PARAM_FIELD_FLAGS = 32,
    UCP_EP_PARAM_FIELD_CONN_REQUEST = 64,
    UCP_EP_PARAM_FIELD_NAME = 128,
    UCP_EP_PARAM_FIELD_LOCAL_SOCK_ADDR = 256,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_ep_params_flags_field {
    UCP_EP_PARAMS_FLAGS_CLIENT_SERVER = 1,
    UCP_EP_PARAMS_FLAGS_NO_LOOPBACK = 2,
    UCP_EP_PARAMS_FLAGS_SEND_CLIENT_ID = 4,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_ep_close_flags_t {
    UCP_EP_CLOSE_FLAG_FORCE = 1,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_ep_perf_param_field {
    UCP_EP_PERF_PARAM_FIELD_MESSAGE_SIZE = 1,
}
pub use self::ucp_ep_perf_param_field as ucp_ep_perf_param_field_t;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_ep_perf_attr_field {
    UCP_EP_PERF_ATTR_FIELD_ESTIMATED_TIME = 1,
}
pub use self::ucp_ep_perf_attr_field as ucp_ep_perf_attr_field_t;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_mem_map_params_field {
    UCP_MEM_MAP_PARAM_FIELD_ADDRESS = 1,
    UCP_MEM_MAP_PARAM_FIELD_LENGTH = 2,
    UCP_MEM_MAP_PARAM_FIELD_FLAGS = 4,
    UCP_MEM_MAP_PARAM_FIELD_PROT = 8,
    UCP_MEM_MAP_PARAM_FIELD_MEMORY_TYPE = 16,
    UCP_MEM_MAP_PARAM_FIELD_EXPORTED_MEMH_BUFFER = 32,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_mem_advise_params_field {
    UCP_MEM_ADVISE_PARAM_FIELD_ADDRESS = 1,
    UCP_MEM_ADVISE_PARAM_FIELD_LENGTH = 2,
    UCP_MEM_ADVISE_PARAM_FIELD_ADVICE = 4,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_lib_attr_field {
    UCP_LIB_ATTR_FIELD_MAX_THREAD_LEVEL = 1,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_context_attr_field {
    UCP_ATTR_FIELD_REQUEST_SIZE = 1,
    UCP_ATTR_FIELD_THREAD_MODE = 2,
    UCP_ATTR_FIELD_MEMORY_TYPES = 4,
    UCP_ATTR_FIELD_NAME = 8,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_worker_attr_field {
    UCP_WORKER_ATTR_FIELD_THREAD_MODE = 1,
    UCP_WORKER_ATTR_FIELD_ADDRESS = 2,
    UCP_WORKER_ATTR_FIELD_ADDRESS_FLAGS = 4,
    UCP_WORKER_ATTR_FIELD_MAX_AM_HEADER = 8,
    UCP_WORKER_ATTR_FIELD_NAME = 16,
    UCP_WORKER_ATTR_FIELD_MAX_INFO_STRING = 32,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_worker_address_attr_field {
    UCP_WORKER_ADDRESS_ATTR_FIELD_UID = 1,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_listener_attr_field {
    UCP_LISTENER_ATTR_FIELD_SOCKADDR = 1,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_conn_request_attr_field {
    UCP_CONN_REQUEST_ATTR_FIELD_CLIENT_ADDR = 1,
    UCP_CONN_REQUEST_ATTR_FIELD_CLIENT_ID = 2,
}
impl ucp_dt_type {
    pub const UCP_DATATYPE_CLASS_MASK: ucp_dt_type = ucp_dt_type::UCP_DATATYPE_GENERIC;
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_dt_type {
    UCP_DATATYPE_CONTIG = 0,
    UCP_DATATYPE_STRIDED = 1,
    UCP_DATATYPE_IOV = 2,
    UCP_DATATYPE_GENERIC = 7,
    UCP_DATATYPE_SHIFT = 3,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_datatype_attr_field {
    UCP_DATATYPE_ATTR_FIELD_PACKED_SIZE = 1,
    UCP_DATATYPE_ATTR_FIELD_BUFFER = 2,
    UCP_DATATYPE_ATTR_FIELD_COUNT = 4,
}
pub const UCP_MEM_MAP_NONBLOCK: _bindgen_ty_4 = _bindgen_ty_4::UCP_MEM_MAP_NONBLOCK;
pub const UCP_MEM_MAP_ALLOCATE: _bindgen_ty_4 = _bindgen_ty_4::UCP_MEM_MAP_ALLOCATE;
pub const UCP_MEM_MAP_FIXED: _bindgen_ty_4 = _bindgen_ty_4::UCP_MEM_MAP_FIXED;
pub const UCP_MEM_MAP_SYMMETRIC_RKEY: _bindgen_ty_4 = _bindgen_ty_4::UCP_MEM_MAP_SYMMETRIC_RKEY;
pub const UCP_MEM_MAP_LOCK: _bindgen_ty_4 = _bindgen_ty_4::UCP_MEM_MAP_LOCK;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _bindgen_ty_4 {
    UCP_MEM_MAP_NONBLOCK = 1,
    UCP_MEM_MAP_ALLOCATE = 2,
    UCP_MEM_MAP_FIXED = 4,
    UCP_MEM_MAP_SYMMETRIC_RKEY = 8,
    UCP_MEM_MAP_LOCK = 16,
}
pub const UCP_MEM_MAP_PROT_LOCAL_READ: _bindgen_ty_5 = _bindgen_ty_5::UCP_MEM_MAP_PROT_LOCAL_READ;
pub const UCP_MEM_MAP_PROT_LOCAL_WRITE: _bindgen_ty_5 = _bindgen_ty_5::UCP_MEM_MAP_PROT_LOCAL_WRITE;
pub const UCP_MEM_MAP_PROT_REMOTE_READ: _bindgen_ty_5 = _bindgen_ty_5::UCP_MEM_MAP_PROT_REMOTE_READ;
pub const UCP_MEM_MAP_PROT_REMOTE_WRITE: _bindgen_ty_5 =
    _bindgen_ty_5::UCP_MEM_MAP_PROT_REMOTE_WRITE;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _bindgen_ty_5 {
    UCP_MEM_MAP_PROT_LOCAL_READ = 1,
    UCP_MEM_MAP_PROT_LOCAL_WRITE = 2,
    UCP_MEM_MAP_PROT_REMOTE_READ = 256,
    UCP_MEM_MAP_PROT_REMOTE_WRITE = 512,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_am_cb_flags {
    UCP_AM_FLAG_WHOLE_MSG = 1,
    UCP_AM_FLAG_PERSISTENT_DATA = 2,
}
impl ucp_send_am_flags {
    pub const UCP_AM_SEND_REPLY: ucp_send_am_flags = ucp_send_am_flags::UCP_AM_SEND_FLAG_REPLY;
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_send_am_flags {
    UCP_AM_SEND_FLAG_REPLY = 1,
    UCP_AM_SEND_FLAG_EAGER = 2,
    UCP_AM_SEND_FLAG_RNDV = 4,
    UCP_AM_SEND_FLAG_COPY_HEADER = 8,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_cb_param_flags {
    UCP_CB_PARAM_FLAG_DATA = 1,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_atomic_op_t {
    UCP_ATOMIC_OP_ADD = 0,
    UCP_ATOMIC_OP_SWAP = 1,
    UCP_ATOMIC_OP_CSWAP = 2,
    UCP_ATOMIC_OP_AND = 3,
    UCP_ATOMIC_OP_OR = 4,
    UCP_ATOMIC_OP_XOR = 5,
    UCP_ATOMIC_OP_LAST = 6,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_stream_recv_flags_t {
    UCP_STREAM_RECV_FLAG_WAITALL = 1,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_op_attr_t {
    UCP_OP_ATTR_FIELD_REQUEST = 1,
    UCP_OP_ATTR_FIELD_CALLBACK = 2,
    UCP_OP_ATTR_FIELD_USER_DATA = 4,
    UCP_OP_ATTR_FIELD_DATATYPE = 8,
    UCP_OP_ATTR_FIELD_FLAGS = 16,
    UCP_OP_ATTR_FIELD_REPLY_BUFFER = 32,
    UCP_OP_ATTR_FIELD_MEMORY_TYPE = 64,
    UCP_OP_ATTR_FIELD_RECV_INFO = 128,
    UCP_OP_ATTR_FIELD_MEMH = 256,
    UCP_OP_ATTR_FLAG_NO_IMM_CMPL = 65536,
    UCP_OP_ATTR_FLAG_FAST_CMPL = 131072,
    UCP_OP_ATTR_FLAG_FORCE_IMM_CMPL = 262144,
    UCP_OP_ATTR_FLAG_MULTI_SEND = 524288,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_req_attr_field {
    UCP_REQUEST_ATTR_FIELD_INFO_STRING = 1,
    UCP_REQUEST_ATTR_FIELD_INFO_STRING_SIZE = 2,
    UCP_REQUEST_ATTR_FIELD_STATUS = 4,
    UCP_REQUEST_ATTR_FIELD_MEM_TYPE = 8,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_am_recv_attr_t {
    UCP_AM_RECV_ATTR_FIELD_REPLY_EP = 1,
    UCP_AM_RECV_ATTR_FLAG_DATA = 65536,
    UCP_AM_RECV_ATTR_FLAG_RNDV = 131072,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_am_handler_param_field {
    UCP_AM_HANDLER_PARAM_FIELD_ID = 1,
    UCP_AM_HANDLER_PARAM_FIELD_FLAGS = 2,
    UCP_AM_HANDLER_PARAM_FIELD_CB = 4,
    UCP_AM_HANDLER_PARAM_FIELD_ARG = 8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_dt_iov {
    pub buffer: *mut ::std::os::raw::c_void,
    pub length: usize,
}
pub type ucp_dt_iov_t = ucp_dt_iov;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_generic_dt_ops {
    pub start_pack: ::std::option::Option<
        unsafe extern "C" fn(
            context: *mut ::std::os::raw::c_void,
            buffer: *const ::std::os::raw::c_void,
            count: usize,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub start_unpack: ::std::option::Option<
        unsafe extern "C" fn(
            context: *mut ::std::os::raw::c_void,
            buffer: *mut ::std::os::raw::c_void,
            count: usize,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub packed_size:
        ::std::option::Option<unsafe extern "C" fn(state: *mut ::std::os::raw::c_void) -> usize>,
    pub pack: ::std::option::Option<
        unsafe extern "C" fn(
            state: *mut ::std::os::raw::c_void,
            offset: usize,
            dest: *mut ::std::os::raw::c_void,
            max_length: usize,
        ) -> usize,
    >,
    pub unpack: ::std::option::Option<
        unsafe extern "C" fn(
            state: *mut ::std::os::raw::c_void,
            offset: usize,
            src: *const ::std::os::raw::c_void,
            length: usize,
        ) -> ucs_status_t,
    >,
    pub finish: ::std::option::Option<unsafe extern "C" fn(state: *mut ::std::os::raw::c_void)>,
}
pub type ucp_generic_dt_ops_t = ucp_generic_dt_ops;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_datatype_attr {
    pub field_mask: u64,
    pub packed_size: usize,
    pub buffer: *const ::std::os::raw::c_void,
    pub count: usize,
}
pub type ucp_datatype_attr_t = ucp_datatype_attr;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_params {
    pub field_mask: u64,
    pub features: u64,
    pub request_size: usize,
    pub request_init: ucp_request_init_callback_t,
    pub request_cleanup: ucp_request_cleanup_callback_t,
    pub tag_sender_mask: u64,
    pub mt_workers_shared: ::std::os::raw::c_int,
    pub estimated_num_eps: usize,
    pub estimated_num_ppn: usize,
    pub name: *const ::std::os::raw::c_char,
}
pub type ucp_params_t = ucp_params;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_lib_attr {
    pub field_mask: u64,
    pub max_thread_level: ucs_thread_mode_t,
}
pub type ucp_lib_attr_t = ucp_lib_attr;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_context_attr {
    pub field_mask: u64,
    pub request_size: usize,
    pub thread_mode: ucs_thread_mode_t,
    pub memory_types: u64,
    pub name: [::std::os::raw::c_char; 32usize],
}
pub type ucp_context_attr_t = ucp_context_attr;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_worker_attr {
    pub field_mask: u64,
    pub thread_mode: ucs_thread_mode_t,
    pub address_flags: u32,
    pub address: *mut ucp_address_t,
    pub address_length: usize,
    pub max_am_header: usize,
    pub name: [::std::os::raw::c_char; 32usize],
    pub max_debug_string: usize,
}
pub type ucp_worker_attr_t = ucp_worker_attr;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_rkey_compare_params {
    pub field_mask: u64,
}
pub type ucp_rkey_compare_params_t = ucp_rkey_compare_params;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_worker_params {
    pub field_mask: u64,
    pub thread_mode: ucs_thread_mode_t,
    pub cpu_mask: ucs_cpu_set_t,
    pub events: ::std::os::raw::c_uint,
    pub user_data: *mut ::std::os::raw::c_void,
    pub event_fd: ::std::os::raw::c_int,
    pub flags: u64,
    pub name: *const ::std::os::raw::c_char,
    pub am_alignment: usize,
    pub client_id: u64,
}
pub type ucp_worker_params_t = ucp_worker_params;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_worker_address_attr {
    pub field_mask: u64,
    pub worker_uid: u64,
}
pub type ucp_worker_address_attr_t = ucp_worker_address_attr;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_ep_evaluate_perf_param_t {
    pub field_mask: u64,
    pub message_size: usize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_ep_evaluate_perf_attr_t {
    pub field_mask: u64,
    pub estimated_time: f64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_listener_attr {
    pub field_mask: u64,
    pub sockaddr: sockaddr_storage,
}
pub type ucp_listener_attr_t = ucp_listener_attr;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_conn_request_attr {
    pub field_mask: u64,
    pub client_address: sockaddr_storage,
    pub client_id: u64,
}
pub type ucp_conn_request_attr_t = ucp_conn_request_attr;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_listener_params {
    pub field_mask: u64,
    pub sockaddr: ucs_sock_addr_t,
    pub accept_handler: ucp_listener_accept_handler_t,
    pub conn_handler: ucp_listener_conn_handler_t,
}
pub type ucp_listener_params_t = ucp_listener_params;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_stream_poll_ep {
    pub ep: ucp_ep_h,
    pub user_data: *mut ::std::os::raw::c_void,
    pub flags: ::std::os::raw::c_uint,
    pub reserved: [u8; 16usize],
}
pub type ucp_stream_poll_ep_t = ucp_stream_poll_ep;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_mem_map_params {
    pub field_mask: u64,
    pub address: *mut ::std::os::raw::c_void,
    pub length: usize,
    pub flags: ::std::os::raw::c_uint,
    pub prot: ::std::os::raw::c_uint,
    pub memory_type: ucs_memory_type_t,
    pub exported_memh_buffer: *const ::std::os::raw::c_void,
}
pub type ucp_mem_map_params_t = ucp_mem_map_params;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_tag_recv_info {
    pub sender_tag: ucp_tag_t,
    pub length: usize,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ucp_request_param_t {
    pub op_attr_mask: u32,
    pub flags: u32,
    pub request: *mut ::std::os::raw::c_void,
    pub cb: ucp_request_param_t__bindgen_ty_1,
    pub datatype: ucp_datatype_t,
    pub user_data: *mut ::std::os::raw::c_void,
    pub reply_buffer: *mut ::std::os::raw::c_void,
    pub memory_type: ucs_memory_type_t,
    pub recv_info: ucp_request_param_t__bindgen_ty_2,
    pub memh: ucp_mem_h,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union ucp_request_param_t__bindgen_ty_1 {
    pub send: ucp_send_nbx_callback_t,
    pub recv: ucp_tag_recv_nbx_callback_t,
    pub recv_stream: ucp_stream_recv_nbx_callback_t,
    pub recv_am: ucp_am_recv_data_nbx_callback_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union ucp_request_param_t__bindgen_ty_2 {
    pub length: *mut usize,
    pub tag_info: *mut ucp_tag_recv_info_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_request_attr_t {
    pub field_mask: u64,
    pub debug_string: *mut ::std::os::raw::c_char,
    pub debug_string_size: usize,
    pub status: ucs_status_t,
    pub mem_type: ucs_memory_type_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_am_handler_param {
    pub field_mask: u64,
    pub id: ::std::os::raw::c_uint,
    pub flags: u32,
    pub cb: ucp_am_recv_callback_t,
    pub arg: *mut ::std::os::raw::c_void,
}
pub type ucp_am_handler_param_t = ucp_am_handler_param;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_am_recv_param {
    pub recv_attr: u64,
    pub reply_ep: ucp_ep_h,
}
unsafe extern "C" {
    pub fn ucp_lib_query(attr: *mut ucp_lib_attr_t) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_config_read(
        env_prefix: *const ::std::os::raw::c_char,
        filename: *const ::std::os::raw::c_char,
        config_p: *mut *mut ucp_config_t,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_config_release(config: *mut ucp_config_t);
}
unsafe extern "C" {
    pub fn ucp_config_modify(
        config: *mut ucp_config_t,
        name: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_config_print(
        config: *const ucp_config_t,
        stream: *mut FILE,
        title: *const ::std::os::raw::c_char,
        print_flags: ucs_config_print_flags_t,
    );
}
unsafe extern "C" {
    pub fn ucp_get_version(
        major_version: *mut ::std::os::raw::c_uint,
        minor_version: *mut ::std::os::raw::c_uint,
        release_number: *mut ::std::os::raw::c_uint,
    );
}
unsafe extern "C" {
    pub fn ucp_get_version_string() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn ucp_init_version(
        api_major_version: ::std::os::raw::c_uint,
        api_minor_version: ::std::os::raw::c_uint,
        params: *const ucp_params_t,
        config: *const ucp_config_t,
        context_p: *mut ucp_context_h,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_cleanup(context_p: ucp_context_h);
}
unsafe extern "C" {
    pub fn ucp_context_query(
        context_p: ucp_context_h,
        attr: *mut ucp_context_attr_t,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_rkey_compare(
        worker: ucp_worker_h,
        rkey1: ucp_rkey_h,
        rkey2: ucp_rkey_h,
        params: *const ucp_rkey_compare_params_t,
        result: *mut ::std::os::raw::c_int,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_context_print_info(context: ucp_context_h, stream: *mut FILE);
}
unsafe extern "C" {
    pub fn ucp_worker_create(
        context: ucp_context_h,
        params: *const ucp_worker_params_t,
        worker_p: *mut ucp_worker_h,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_worker_destroy(worker: ucp_worker_h);
}
unsafe extern "C" {
    pub fn ucp_worker_query(worker: ucp_worker_h, attr: *mut ucp_worker_attr_t) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_worker_print_info(worker: ucp_worker_h, stream: *mut FILE);
}
unsafe extern "C" {
    pub fn ucp_worker_release_address(worker: ucp_worker_h, address: *mut ucp_address_t);
}
unsafe extern "C" {
    pub fn ucp_worker_address_query(
        address: *mut ucp_address_t,
        attr: *mut ucp_worker_address_attr_t,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_worker_progress(worker: ucp_worker_h) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn ucp_stream_worker_poll(
        worker: ucp_worker_h,
        poll_eps: *mut ucp_stream_poll_ep_t,
        max_eps: usize,
        flags: ::std::os::raw::c_uint,
    ) -> isize;
}
unsafe extern "C" {
    pub fn ucp_worker_get_efd(worker: ucp_worker_h, fd: *mut ::std::os::raw::c_int)
        -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_worker_wait(worker: ucp_worker_h) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_worker_wait_mem(worker: ucp_worker_h, address: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn ucp_worker_arm(worker: ucp_worker_h) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_worker_signal(worker: ucp_worker_h) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_listener_create(
        worker: ucp_worker_h,
        params: *const ucp_listener_params_t,
        listener_p: *mut ucp_listener_h,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_listener_destroy(listener: ucp_listener_h);
}
unsafe extern "C" {
    pub fn ucp_listener_query(
        listener: ucp_listener_h,
        attr: *mut ucp_listener_attr_t,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_conn_request_query(
        conn_request: ucp_conn_request_h,
        attr: *mut ucp_conn_request_attr_t,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_request_query(
        request: *mut ::std::os::raw::c_void,
        attr: *mut ucp_request_attr_t,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_ep_create(
        worker: ucp_worker_h,
        params: *const ucp_ep_params_t,
        ep_p: *mut ucp_ep_h,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_ep_close_nbx(ep: ucp_ep_h, param: *const ucp_request_param_t) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_listener_reject(
        listener: ucp_listener_h,
        conn_request: ucp_conn_request_h,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_ep_print_info(ep: ucp_ep_h, stream: *mut FILE);
}
unsafe extern "C" {
    pub fn ucp_ep_flush_nbx(ep: ucp_ep_h, param: *const ucp_request_param_t) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_ep_evaluate_perf(
        ep: ucp_ep_h,
        param: *const ucp_ep_evaluate_perf_param_t,
        attr: *mut ucp_ep_evaluate_perf_attr_t,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_mem_map(
        context: ucp_context_h,
        params: *const ucp_mem_map_params_t,
        memh_p: *mut ucp_mem_h,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_mem_unmap(context: ucp_context_h, memh: ucp_mem_h) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_mem_query(memh: ucp_mem_h, attr: *mut ucp_mem_attr_t) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_mem_print_info(
        mem_spec: *const ::std::os::raw::c_char,
        context: ucp_context_h,
        stream: *mut FILE,
    );
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_mem_advice {
    UCP_MADV_NORMAL = 0,
    UCP_MADV_WILLNEED = 1,
}
pub use self::ucp_mem_advice as ucp_mem_advice_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_mem_advise_params {
    pub field_mask: u64,
    pub address: *mut ::std::os::raw::c_void,
    pub length: usize,
    pub advice: ucp_mem_advice_t,
}
pub type ucp_mem_advise_params_t = ucp_mem_advise_params;
unsafe extern "C" {
    pub fn ucp_mem_advise(
        context: ucp_context_h,
        memh: ucp_mem_h,
        params: *mut ucp_mem_advise_params_t,
    ) -> ucs_status_t;
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_memh_pack_params_field {
    UCP_MEMH_PACK_PARAM_FIELD_FLAGS = 1,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_memh_pack_flags {
    UCP_MEMH_PACK_FLAG_EXPORT = 1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_memh_pack_params {
    pub field_mask: u64,
    pub flags: u64,
}
pub type ucp_memh_pack_params_t = ucp_memh_pack_params;
unsafe extern "C" {
    pub fn ucp_memh_pack(
        memh: ucp_mem_h,
        params: *const ucp_memh_pack_params_t,
        buffer_p: *mut *mut ::std::os::raw::c_void,
        buffer_size_p: *mut usize,
    ) -> ucs_status_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_memh_buffer_release_params {
    pub field_mask: u64,
}
pub type ucp_memh_buffer_release_params_t = ucp_memh_buffer_release_params;
unsafe extern "C" {
    pub fn ucp_memh_buffer_release(
        buffer: *mut ::std::os::raw::c_void,
        params: *const ucp_memh_buffer_release_params_t,
    );
}
unsafe extern "C" {
    pub fn ucp_ep_rkey_unpack(
        ep: ucp_ep_h,
        rkey_buffer: *const ::std::os::raw::c_void,
        rkey_p: *mut ucp_rkey_h,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_rkey_ptr(
        rkey: ucp_rkey_h,
        raddr: u64,
        addr_p: *mut *mut ::std::os::raw::c_void,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_rkey_destroy(rkey: ucp_rkey_h);
}
unsafe extern "C" {
    pub fn ucp_worker_set_am_recv_handler(
        worker: ucp_worker_h,
        param: *const ucp_am_handler_param_t,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_am_send_nbx(
        ep: ucp_ep_h,
        id: ::std::os::raw::c_uint,
        header: *const ::std::os::raw::c_void,
        header_length: usize,
        buffer: *const ::std::os::raw::c_void,
        count: usize,
        param: *const ucp_request_param_t,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_am_recv_data_nbx(
        worker: ucp_worker_h,
        data_desc: *mut ::std::os::raw::c_void,
        buffer: *mut ::std::os::raw::c_void,
        count: usize,
        param: *const ucp_request_param_t,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_am_data_release(worker: ucp_worker_h, data: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn ucp_stream_send_nbx(
        ep: ucp_ep_h,
        buffer: *const ::std::os::raw::c_void,
        count: usize,
        param: *const ucp_request_param_t,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_tag_send_nbx(
        ep: ucp_ep_h,
        buffer: *const ::std::os::raw::c_void,
        count: usize,
        tag: ucp_tag_t,
        param: *const ucp_request_param_t,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_tag_send_sync_nbx(
        ep: ucp_ep_h,
        buffer: *const ::std::os::raw::c_void,
        count: usize,
        tag: ucp_tag_t,
        param: *const ucp_request_param_t,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_stream_recv_nbx(
        ep: ucp_ep_h,
        buffer: *mut ::std::os::raw::c_void,
        count: usize,
        length: *mut usize,
        param: *const ucp_request_param_t,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_stream_recv_data_nb(ep: ucp_ep_h, length: *mut usize) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_tag_recv_nbx(
        worker: ucp_worker_h,
        buffer: *mut ::std::os::raw::c_void,
        count: usize,
        tag: ucp_tag_t,
        tag_mask: ucp_tag_t,
        param: *const ucp_request_param_t,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_tag_probe_nb(
        worker: ucp_worker_h,
        tag: ucp_tag_t,
        tag_mask: ucp_tag_t,
        remove: ::std::os::raw::c_int,
        info: *mut ucp_tag_recv_info_t,
    ) -> ucp_tag_message_h;
}
unsafe extern "C" {
    pub fn ucp_tag_msg_recv_nbx(
        worker: ucp_worker_h,
        buffer: *mut ::std::os::raw::c_void,
        count: usize,
        message: ucp_tag_message_h,
        param: *const ucp_request_param_t,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_put_nbx(
        ep: ucp_ep_h,
        buffer: *const ::std::os::raw::c_void,
        count: usize,
        remote_addr: u64,
        rkey: ucp_rkey_h,
        param: *const ucp_request_param_t,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_get_nbx(
        ep: ucp_ep_h,
        buffer: *mut ::std::os::raw::c_void,
        count: usize,
        remote_addr: u64,
        rkey: ucp_rkey_h,
        param: *const ucp_request_param_t,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_atomic_op_nbx(
        ep: ucp_ep_h,
        opcode: ucp_atomic_op_t,
        buffer: *const ::std::os::raw::c_void,
        count: usize,
        remote_addr: u64,
        rkey: ucp_rkey_h,
        param: *const ucp_request_param_t,
    ) -> ucs_status_ptr_t;
}
unsafe extern "C" {
    pub fn ucp_request_check_status(request: *mut ::std::os::raw::c_void) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_tag_recv_request_test(
        request: *mut ::std::os::raw::c_void,
        info: *mut ucp_tag_recv_info_t,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_stream_recv_request_test(
        request: *mut ::std::os::raw::c_void,
        length_p: *mut usize,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_request_cancel(worker: ucp_worker_h, request: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn ucp_stream_data_release(ep: ucp_ep_h, data: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn ucp_request_free(request: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn ucp_request_alloc(worker: ucp_worker_h) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn ucp_dt_create_generic(
        ops: *const ucp_generic_dt_ops_t,
        context: *mut ::std::os::raw::c_void,
        datatype_p: *mut ucp_datatype_t,
    ) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_dt_destroy(datatype: ucp_datatype_t);
}
unsafe extern "C" {
    pub fn ucp_dt_query(datatype: ucp_datatype_t, attr: *mut ucp_datatype_attr_t) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_worker_fence(worker: ucp_worker_h) -> ucs_status_t;
}
unsafe extern "C" {
    pub fn ucp_worker_flush_nbx(
        worker: ucp_worker_h,
        param: *const ucp_request_param_t,
    ) -> ucs_status_ptr_t;
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ucp_ep_attr_field {
    UCP_EP_ATTR_FIELD_NAME = 1,
    UCP_EP_ATTR_FIELD_LOCAL_SOCKADDR = 2,
    UCP_EP_ATTR_FIELD_REMOTE_SOCKADDR = 4,
    UCP_EP_ATTR_FIELD_TRANSPORTS = 8,
    UCP_EP_ATTR_FIELD_USER_DATA = 16,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucp_ep_attr {
    pub field_mask: u64,
    pub name: [::std::os::raw::c_char; 32usize],
    pub local_sockaddr: sockaddr_storage,
    pub remote_sockaddr: sockaddr_storage,
    pub transports: ucp_transports_t,
    pub user_data: *mut ::std::os::raw::c_void,
}
pub type ucp_ep_attr_t = ucp_ep_attr;
unsafe extern "C" {
    pub fn ucp_ep_query(ep: ucp_ep_h, attr: *mut ucp_ep_attr_t) -> ucs_status_t;
}
